version: "3"
services:
        mysql:
                image: mysql_local
                volumes:
                        - ./mysql_data/:/var/lib/mysql/
                ports: 
                        - "3306:3306"
        exchange-service-app:
                depends_on:
                        - mysql
                build:
                        context: ./
                        dockerfile: exchangeDockerFile
                ports:
                        - "9090:9090"
                hostname: ip-172-31-38-251          
